ifeq ($(LVGL),1)

CCFLAGS += -I$(TOP)/libraries/thirdparty/lvgl

# lvgl
DIRS += $(shell find $(TOP)/libraries/thirdparty/lvgl/src -type d)

# lvgl demo
DIRS += $(shell find $(TOP)/libraries/thirdparty/lvgl/demos -type d)

#TFT_eSPI
CCFLAGS += -I$(TOP)/libraries/thirdparty/TFT_eSPI
DIRS += libraries/thirdparty/TFT_eSPI
endif
