ifeq ($(OPENAMP),1)

#OpenAMP libmetal log on
CCFLAGS += -DDEFAULT_LOGGER_ON -DMETAL_INTERNAL
# virt_uart
CCFLAGS += -DVIRTIOCON -DVIRTIO_SLAVE_ONLY
#OpenAMP headers files
CCFLAGS += -I$(TOP)/cores/arduino/sunplus/OpenAMP
CCFLAGS += -I$(TOP)/system/Middlewares/OpenAMP
CCFLAGS += -I$(TOP)/system/Middlewares/OpenAMP/libmetal/lib/include
CCFLAGS += -I$(TOP)/system/Middlewares/OpenAMP/open-amp/lib/include
CCFLAGS += -I$(TOP)/system/Middlewares/OpenAMP/open-amp/apps/machine/sunplus
CCFLAGS += -I$(TOP)/system/Middlewares/OpenAMP/virt_driver

DIRS += $(TOP)/cores/arduino/sunplus/OpenAMP
DIRS += $(TOP)/cores/arduino/sunplus/OpenAMP/libmetal
DIRS += $(TOP)/cores/arduino/sunplus/OpenAMP/libmetal/generic
ifeq ($(CHIP),Q628)
DIRS += $(TOP)/cores/arduino/sunplus/OpenAMP/libmetal/generic/a926
else
DIRS += $(TOP)/cores/arduino/sunplus/OpenAMP/libmetal/generic/cm4
endif
DIRS += $(TOP)/cores/arduino/sunplus/OpenAMP/open-amp/machine
DIRS += $(TOP)/cores/arduino/sunplus/OpenAMP/open-amp/proxy
DIRS += $(TOP)/cores/arduino/sunplus/OpenAMP/open-amp/remoteproc
DIRS += $(TOP)/cores/arduino/sunplus/OpenAMP/open-amp/rpmsg
DIRS += $(TOP)/cores/arduino/sunplus/OpenAMP/open-amp/virtio
DIRS += $(TOP)/system/Middlewares/OpenAMP/virt_driver

endif
