ifeq ($(LVGL),1)

CCFLAGS += -I$(TOP)/libraries/lvgl

# lvgl
DIRS += $(shell find $(TOP)/libraries/lvgl/src -type d)

# lvgl demo
DIRS += $(shell find $(TOP)/libraries/lvgl/demos -type d)

#TFT_eSPI
CCFLAGS += -I$(TOP)/libraries/TFT_eSPI
DIRS += libraries/TFT_eSPI
endif
